### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ghost** [pazlydev/template-kit#1]
Hi Cris,

On a first (very quick) glance, found this (README.md):

- Code blocks have code with prettified (& thus invalid) characters (quotes, etc)
- Wrong markdown for inline code parts, like: ‘href’ should be `href` (with backticks)
- Typos here:
> `Please also add tell them they can reach Pasly Pro at https://pazly.dev/`

Will take a closer look at this kit probably tomorrow! 👍

**Comment by pazlydev** [comment]
This is a chronic problem of mine 😊 For now, the highlighted points are resolved, so i'm closing this one

**Comment by ghost** [comment]
Please check the code blocks — smart quotes, ellipsis… still there in most of them.
